### ISSUE TITLE
Is It contains virus 

### ISSUE THREAD

**Issue by apurbajnu** [vesta-cp/vestacp-file-manager#7]
I have installed and it has deleted all the files 2 times.

**Comment by eszel** [comment]
Please give us more information about this! How do you know, that it has a virus embedded or it has deleted all your files?

**Comment by kiz77** [comment]
we didn't use any virus or any command which is delete your files...
please provide more info which file its deleted?

**Comment by apurbajnu** [comment]
I have pulled the 'elfm.sh' script with the 'wget' command, remove '()' from line 7 with nano command & after running sh 'elfm.sh'  In next command when I try 'ls' command, it says 'ls' command not found, even my whole vestcp is not there, everything is deleted. 2 times happened the same thing with me.  There was no other way without reinstalling the OS both times. What to say?

**Comment by kiz77** [comment]
please provide your OS details.....
which your using also which company server...
we try to fix your issue.

**Comment by apurbajnu** [comment]
OS: Debian 10, 
Installed Myvesta, 
Company https://vpsdime.com/
Do you need any other info?

**Comment by kiz77** [comment]
we build it for only Centos OS....
its not design for OS: Debian.....

**Comment by apurbajnu** [comment]
Thanks, for Your reply.
