### ISSUE TITLE
How to show ELFM is user accounts?

### ISSUE THREAD

**Issue by mdimrannazir** [vesta-cp/vestacp-file-manager#8]
After installing ELFM in my vesta admin account, It's working fine without any kinds of issues.
Here is an admin account screenshot where everything looks fine.
Screenshot:  https://prntscr.com/16l29xu

The problem occurs when I create a new user account in Vesta and log in to that account. There is no ELFM file management option on the top bar.
Below I shared a screenshot of the user account which I created from the admin account. The "ELFM" not showing in the user account.
Screenshot: https://prntscr.com/16l1yzl

How can I show the "ELFM" option in the user accounts?

**Comment by kiz77** [comment]
sorry but currently EL file manager supported only admin user...
